### ISSUE TITLE
Please help ..How to compile this code ?

### ISSUE THREAD

**Issue by uttaran18** [speed47/StairwayLeds#1]
I am using Arduino ide but i cannot compile it

**Comment by speed47** [comment]
Hello,

I admit it misses some documentation about that. I no longer use the Arduino IDE, because I found out it was hiding some errors/warnings, so if you're under Linux, you can use `./configure` directly.
In any case, it should still work correctly from the Arduino IDE, as long as you have the proper librairies installed, and Teensyduino installed too. Is this the case ?
Which error message do you get?

**Comment by uttaran18** [comment]
is it possible to port this from octows2811 to fastled?

**Comment by uttaran18** [comment]
thanks for the reply. I ll try it on ubuntu

**Comment by uttaran18** [comment]
while using ./configure it says "configure: coudln't find a valid ARM compiler under required/hardware/tools"

**Comment by uttaran18** [comment]
Yes I have both Arduino and teensyduino installed

**Comment by speed47** [comment]
Can you share the complete command line you type, and the complete error message you get?
You have to specify a few options, such as where your teensyduino-augmented arduino installation is to be found.
Example:

`./configure --teensy-version 31 --arduino-path ~/arduino-1.0.6`

**Comment by uttaran18** [comment]
Hi .... Thanks a lot for the help .. I have successfully compiled and run the code . I was wondering if it is possible to trigger the running pattern again say if a second person follows the first person  when the lights starts to turn off , then it is possible that the second person will be left in the dark half way through .. 

https://youtu.be/ur4Sx7ajRYU

**Comment by uttaran18** [comment]
And again thanks a lot for the reply .. 😊
